### ISSUE TITLE
ghc-8.6.5

### ISSUE THREAD

**Issue by rd--** [justinethier/husk-scheme#213]
hello - thanks for husk-scheme, it's excellent! - unfortunately it won't compile with new-ish ghc (here 8.6.5 / debian testing) -copy of the build report below - it'd be lovely if this could be fixed - best, rd

Build log ( .cabal/logs/ghc-8.6.5/husk-scheme-3.19.3-COkDegp2uzWKHUgyiS0gmI.log ):
cabal: Entering directory '/tmp/cabal-tmp-178121/husk-scheme-3.19.3'
Configuring husk-scheme-3.19.3...
Preprocessing library for husk-scheme-3.19.3..
Building library for husk-scheme-3.19.3..
[ 1 of 17] Compiling Language.Scheme.Types ( hs-src/Language/Scheme/Types.hs, dist/build/Language/Scheme/Types.o )

hs-src/Language/Scheme/Types.hs:99:1: warning: [-Wdeprecations]
    Module ‘Control.Monad.Error’ is deprecated:
      Use "Control.Monad.Except" instead
   |
99 | import Control.Monad.Error
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^

hs-src/Language/Scheme/Types.hs:168:10: warning: [-Wdeprecations]
    In the use of type constructor or class ‘Error’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"
    |
168 | instance Error LispError where
    |          ^^^^^

hs-src/Language/Scheme/Types.hs:168:10: warning: [-Wdeprecations]
    In the use of type constructor or class ‘Error’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"
    |
168 | instance Error LispError where
    |          ^^^^^

hs-src/Language/Scheme/Types.hs:186:22: warning: [-Wdeprecations]
    In the use of type constructor or class ‘ErrorT’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"
    |
186 | type IOThrowsError = ErrorT LispError IO
    |                      ^^^^^^
[ 2 of 17] Compiling Language.Scheme.Plugins.CPUTime ( hs-src/Language/Scheme/Plugins/CPUTime.hs, dist/build/Language/Scheme/Plugins/CPUTime.o )

hs-src/Language/Scheme/Plugins/CPUTime.hs:23:1: warning: [-Wdeprecations]
    Module ‘Control.Monad.Error’ is deprecated:
      Use "Control.Monad.Except" instead
   |
23 | import Control.Monad.Error
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^
[ 3 of 17] Compiling Language.Scheme.Parser ( hs-src/Language/Scheme/Parser.hs, dist/build/Language/Scheme/Parser.o )

hs-src/Language/Scheme/Parser.hs:49:1: warning: [-Wdeprecations]
    Module ‘Control.Monad.Error’ is deprecated:
      Use "Control.Monad.Except" instead
   |
49 | import Control.Monad.Error
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^
[ 4 of 17] Compiling Language.Scheme.Numerical ( hs-src/Language/Scheme/Numerical.hs, dist/build/Language/Scheme/Numerical.o )

hs-src/Language/Scheme/Numerical.hs:183:3: error:
    • No instance for (Control.Monad.Fail.MonadFail (Either LispError))
        arising from a do statement
        with the failable pattern ‘List [n1', n2']’
    • In a stmt of a 'do' block: List [n1', n2'] <- numCast [n1, n2]
      In the expression:
        do List [n1', n2'] <- numCast [n1, n2]
           result <- cmp n1' n2'
           case result of
             Bool True -> numBoolBinopCompare cmp n2' ns
             _ -> return $ Bool False
      In an equation for ‘numBoolBinopCompare’:
          numBoolBinopCompare cmp n1 (n2 : ns)
            = do List [n1', n2'] <- numCast [n1, ....]
                 result <- cmp n1' n2'
                 case result of
                   Bool True -> numBoolBinopCompare cmp n2' ns
                   _ -> return $ Bool False
    |
183 |   List [n1', n2'] <- numCast [n1, n2]
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '/tmp/cabal-tmp-178121/husk-scheme-3.19.3'

**Comment by svenkeidel** [comment]
https://github.com/justinethier/husk-scheme/pull/212 fixes the compile error and https://github.com/justinethier/husk-scheme/pull/214 fixes the `ErrorT` warnings.

**Comment by justinethier** [comment]
Thanks everyone! Is husk good to go on 8.6.5 now?

**Comment by rd--** [comment]
hello all - yes, current git (20fbaa1c) compiles with 8.6.5 here - thanks very kindly! - best, rohan

**Comment by justinethier** [comment]
Great, thanks for verifying! I will will close this issue.

**Comment by svenkeidel** [comment]
@justinethier, thanks for merging.
For the record, I tested with 8.8.2 and it worked.
